services:
  - type: web
    name: shiftize
    buildCommand: expo export:web
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        statusCode: 200
