services:
  - type: web
    name: shiftee-pwa
    buildCommand: expo export:web
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
