

export const SHIFT_HOURS = {

  START_HOUR_INCLUSIVE: 9,

  AFTERNOON_START_HOUR_INCLUSIVE: 13,

  END_HOUR_INCLUSIVE: 22,

  TIME_INTERVAL_MINUTES: 30,
};

export const MAX_CLASSES_PER_SHIFT_INCLUSIVE = 6;

export const BREAKPOINTS = {

  SMALL_DEVICE_MAX_WIDTH_EXCLUSIVE: 375,

  MOBILE_MAX_WIDTH_INCLUSIVE: 600,

  COMPACT_VIEW_MIN_WIDTH_INCLUSIVE: 500,

  TABLET_MIN_WIDTH_INCLUSIVE: 768,

  TABLET_MAX_WIDTH_EXCLUSIVE: 1024,

  DESKTOP_MIN_WIDTH_INCLUSIVE: 1280,
};

export const DATE_VALIDATION = {

  MAX_FUTURE_YEARS_INCLUSIVE: 2,

  MAX_PAST_YEARS_INCLUSIVE: 5,
};

export const SECURITY_TIMEOUTS = {

  CSRF_TOKEN_LIFETIME_MS: 30 * 60 * 1000,

  RATE_LIMIT_BUCKET_MAX_AGE_MS: 60 * 60 * 1000,
};
